### PR TITLE
Upgrade to work with Nexus 3.30.1

### LINKED ISSUE #26: Tag 0.1.5 fails install on Nexus v3.30.0-01
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Trying to install the plugin using a kar file and Nexus v3.30.0-01

* **What feature or behavior is this required for?**
I wanted to make use of the Puppet recipe to create a Nexus Repository

* **How could we solve this issue? (Not knowing is okay!)***
Upgrade code to work with Nexus v3.30

* **Anything else?**
2021-03-26 15:35:57,250+0000 ERROR [FelixStartLevel]  *SYSTEM Felix - Bundle org.sonatype.nexus.extender [93] EventDispatcher: Error during dispatch. (com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item)
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
        at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173)
        at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160)
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at org.eclipse.sisu.launch.SisuBundlePlan.inject(SisuBundlePlan.java:78)
        at org.eclipse.sisu.launch.SisuBundlePlan.prepare(SisuBundlePlan.java:50)
        at org.eclipse.sisu.launch.SisuTracker.prepare(SisuTracker.java:186)
        at org.sonatype.nexus.extender.NexusBundleTracker.prepare(NexusBundleTracker.java:69)
        at org.eclipse.sisu.launch.SisuTracker.addingBundle(SisuTracker.java:129)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:415)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
        at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
        at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2231)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to load cache item
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 35 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/sonatype/nexus/repository/mime/ContentValidator
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.google.inject.internal.cglib.core.$ReflectUtils.defineClass(ReflectUtils.java:467)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
        ... 52 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonatype.nexus.repository.mime.ContentValidator
        at java.lang.ClassLoader.findClass(ClassLoader.java:523)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at com.google.inject.internal.BytecodeGen$BridgeClassLoader.classicLoadClass(BytecodeGen.java:424)
        at com.google.inject.internal.BytecodeGen$BridgeClassLoader.loadClass(BytecodeGen.java:419)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 61 common frames omitted

### PR DESCRIPTION
**Pull request by cardil**
This pull request makes the following changes:
* Updates the Nexus parent to 3.30.1
* Fixes integration test of PuppetMergingHandlerTest
* Adds new e2e test PuppetPluginIT that checks if Nexus boots properly with this plugin

It relates to the following issue #s:
* Fixes #26

### CODE REVIEW

**Comment by cardil** [comment]
For everyone that wants to eagerly try this PR builds, I've built the plugin and hosted it here:

- [nexus-repository-puppet-0.1.6-SNAPSHOT.jar](https://wavesoftware.pl/files/nexus-repository-puppet/nexus-repository-puppet-0.1.6-SNAPSHOT.jar)
- [nexus-repository-puppet-0.1.6-SNAPSHOT-bundle.kar](https://wavesoftware.pl/files/nexus-repository-puppet/nexus-repository-puppet-0.1.6-SNAPSHOT-bundle.kar)

**Comment by cardil** [comment]
This PR supersedes #20

**Comment by cardil** [comment]
@bhamail @aornatovskyy @DarthHater Can we merge this, please?

**Comment by bhamail** [comment]
@cardil Done. Thanks for the PR, and for pinging us about it! Please holler if any surprises pop up.

**Pull request merged**
