### PR TITLE
Support for Puppet Group repository

### LINKED ISSUE #2: Hosted Support
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Host puppet modules in Nexus Repository

* **What feature or behavior is this required for?**
Basically so people can host their own private modules

* **How could we solve this issue? (Not knowing is okay!)**
You can take a look at how we've done this for other formats and implement it! Helm has a Hosted implementation and you can likely look at that for inspiration

* **Anything else?**
Have fun! PRs welcome!

### LINKED ISSUE #12: Return modules dependencies
* **What are you trying to do?**
Puppet modules contain dependencies. For example `puppetlabs-ntp` depends on `puppetlabs-stdlib`. 
On calls to `v3/releases`, I would like to return the dependencies of a Puppet module inside the field `metadata`.

* **What feature or behavior is this required for?**
This is necessary so installing modules using `$ puppet module install` will bring also the dependencies, like in the following example.
```
$ puppet module install puppetlabs-ntp --module_repository=http://localhost:8081/repository/puppet-hosted
Notice: Preparing to install into /home/camaral/.puppet/etc/code/modules ...
Notice: Created target directory /home/camaral/.puppet/etc/code/modules
Notice: Downloading from http://localhost:8081/repository/puppet-hosted ...
Notice: Installing -- do not interrupt ...
/home/camaral/.puppet/etc/code/modules
└─┬ puppetlabs-ntp (v7.3.0)
  └── puppetlabs-stdlib (v5.1.0)
```

* **How could we solve this issue? (Not knowing is okay!)**
It is necessary to save the dependencies on the Asset's Attributes when it is uploaded. Calls to `/release`  must use the saved data to return the dependencies. 

* **Anything else?**
I will send a pull request for that in a minute.
As I am interested on the hosted repository, I will apply the PR on the branch, if that is fine.

### LINKED ISSUE #15: Add maven wrapper
Adding maven wrapper to the project makes it easier to start and keep everybody on the same maven version. Maven is pretty stable and does not break often, but it still good to keep everyone in the same page.

* **What are you trying to do?**
Add mvnw to the project

* **What feature or behavior is this required for?**
It makes easier to keep compatibility between the developers.

* **How could we solve this issue? (Not knowing is okay!)**
Run `mvn -N io.takari:maven:wrapper` and commit the files.

* **Anything else?**
Let me know if this suggestion is something that you guys would like to have. If so, I can submit a Pull Request.

### LINKED ISSUE #17: Group Support
Puppet repository should have a group feature implemented. If so integration of private and proxied modules can be achived.

When support for group repositories is added users can host their provate modules that rely on public dependencies. Installation of such modules will be seamless.

Solving this issue will need #2 (hosted support) be fixed earlier.

### PR DESCRIPTION
**Pull request by cardil**
Group repository is listed as one of the types. User can add other Puppet repositories to it. Content is successfully proxies from on of the sources. Metadata merging was done in simple way, on asumption that single package will be present only in one repository.

Adding also a integration test to assert proper operation. Test is designed in that way so Nexus should look at grouped repositories and merge metadata entries so if module is on second repository it should be returned.

This pull request is based on work on `hosted_poc` branch and also fixes provided by @camaral

All three types of Puppet repositories listed and functional:

repo list

Installing a hosted private module with dependencies proxied from Puppet Forge from command line:

usage

Is it is based on others work it efectivly relates to the following issue #s:
* Fixes #2 
* Fixes #12 
* Fixes #15 

This issue directly fixes #17

### CODE REVIEW

**Comment by cardil** [comment]
I've already sign CLA.

It seams that some commits of @camaral aren't connected to his GH account. I've managed to reach him so he connect this account. In that way it can be verified. But I can skip them if he doesn't do that.

But there's issue of commits by Daniel Sauble `<dsauble@sonatype.com>` @djsauble. It seems like his email isn't connected also and his profile says that his no longer work in Sonatype.

@DarthHater what to do with Daniel's contributions? Maybe you can rebase them as they ware done when he was working for Sonatype? They are mixed with your. 😵

**Comment by cardil** [comment]
I'm publishing this plugin with my changes here: https://dl.bintray.com/wavesoftware/mvn-github-forks/org/sonatype/nexus/plugins/nexus-repository-puppet/

Sharing it if someone would like to use it eagerly.

**Comment by camaral** [comment]
I fixed my email issue. Sorry for the delay.
On the other hand, @DarthHater told me on another pull request that he didn't want maven wrapper on his repository.
So I imagine that he will not approve this PR either.

**Comment by christophvw** [comment]
Any updates on this? I really need the hosted function for puppet.

**Comment by christophvw** [comment]
@cardil could you provide a .kar file of your improved plugin please?

**Comment by cardil** [comment]
> @cardil could you provide a .kar file of your improved plugin please?

What is `.kar` file? 

I'm publishing this plugin with my changes here: https://dl.bintray.com/wavesoftware/mvn-github-forks/org/sonatype/nexus/plugins/nexus-repository-puppet - you can install this jar, as any other custom plugin.

**Comment by christophvw** [comment]
All other plugins I downloaded so far came as .kar files, so I expected this to be the standard way of installing plugins.

see:
https://help.sonatype.com/repomanager3/bundle-development/installing-bundles

**Comment by DarthHater** [comment]
Went ahead and merged this in, appreciate the contribution, and the effort on getting us to take a look. @djsauble worked at Sonatype when he wrote this, and was under a specific CLA for working here, which bots are not great at figuring out apparently :)

**Pull request merged**
